name: Deploy to AWS EC2

on:
  push:
    branches: 
      - main  # Trigger on push to main branch
      - feature/terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Plan Terraform
      - name: Plan Terraform
        run: terraform plan

      # Apply Terraform
      - name: Apply Terraform
        run: terraform apply -auto-approve