name: Deploy to AWS EC2

on:
  push:
    branches: 
      - main  # Trigger on push to main branch
      - feature/terraform

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      # SSH into EC2 and deploy
      - name: SSH into EC2 and deploy
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Define EC2 details
          EC2_USER="ec2-user"   # EC2 username (e.g., ubuntu, ec2-user, etc.)
          echo "The vars b4 ssh are: $EC2_DIR $EC2_USER $EC2_HOST"

          # SSH into EC2 instance and execute deployment commands
          ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} << 'EOF'
            set -e  # Exit on error

            EC2_DIR="/home/ec2-user/nex-gen-cms"  # Path to project on the EC2 instance
            # Echo the project directory
            echo "The vars after ssh are: $EC2_DIR"

            # Navigate to the project directory
            cd ${EC2_DIR}
            
            # Pull the latest changes from the main branch
            git fetch origin
            git checkout main
            git pull origin main

            # Run the Go service
            nohup go run cmd/main.go > app.log 2>&1 &

            echo "Deployment complete."
          EOF